- name: "Query for existing NAT gateway(s)"
  ec2_vpc_nat_gateway_info:
    profile: "{{ aws_vpc_delete.profile }}"
    region: "{{ aws_vpc_delete.region }}"
    filters:
      vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
  register: nat_gateways

- name: "Delete nat gateway and release EIP"
  ec2_vpc_nat_gateway:
    profile: "{{ aws_vpc_delete.profile }}"
    region: "{{ aws_vpc_delete.region }}"
    nat_gateway_id: "{{ item.nat_gateway_id }}"
    release_eip: "{{ aws_vpc_delete.release_elastic_ip | default('yes') }}"
    state: "absent"
    wait: yes
    wait_timeout: 300
  with_items: "{{ nat_gateways.result }}"
