- name: "Get details on VPC peer(s)"
  ec2_vpc_peering_info:
    profile: "{{ aws_vpc_delete.profile }}"
    region: "{{ aws_vpc_delete.region }}"
    filters:
      requester-vpc-info.vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
  register: vpc_peers

- name: "Delete peering connection"
  ec2_vpc_peer:
    profile: "{{ aws_vpc_delete.profile }}"
    region: "{{ aws_vpc_delete.region }}"
    peering_id: "{{ item.vpc_peering_connection_id }}"
    state: "absent"
  with_items: "{{ vpc_peers.result }}"
