- name: "Query for any existing subnet(s)"
  ec2_vpc_subnet_info:
    profile: "{{ aws_vpc_delete.profile }}"
    region: "{{ aws_vpc_delete.region }}"
    filters:
      vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
  register: subnet_info

- name: "Delete subnets"
  ec2_vpc_subnet:
    profile: "{{ aws_vpc_delete.profile }}"
    region: "{{ aws_vpc_delete.region }}"
    vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
    cidr: "{{ item.cidr_block }}"
    state: "absent"
  with_items: "{{ subnet_info.subnets }}"
