  tasks:
      - name: 'Find stale ec2 instances'
        ec2_instance_find:
            region: '{{ item }}'
            uptime: '{{ uptime }}'
            filter: '{{ instance_filters }}'
            exclude: '{{ instance_excludes }}'
        register: ec2_instances
        with_items: '{{ instance_regions }}'

      - name: 'Terminate matching instances'
        ec2:
            region: '{{ item.item }}'
            instance_ids: '{{ item.results|map(attribute="InstanceId")|list }}'
            state: 'absent'
        with_items: '{{ ec2_instances.results }}'
        when: '{{ item.results|default([])|length }} > 0 '
