---
- name: this Ansible Playbook will terminate un-tagged instances
  hosts: localhost
  gather_facts: false
  vars:
    ec2_region: "{{ your_region | default('us-east-2') }}"
  tasks:
    - name: grab info for un-tagged instances
      community.aws.ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          instance-state-name: running
      register: ec2_node_info

    - name: set the untagged to a var
      set_fact:
        missing_tag: "{{ ec2_node_info.instances | selectattr('tags.owner', 'undefined') | map(attribute='instance_id') | list }}"

    - name: diplay AWS missing tag results
      debug:
        msg: "{{ lookup('template', 'templates/missing_tag.j2') }}"

    # - name: Terminate every un-tagged running instance in a region.
    #   amazon.aws.ec2:
    #     region: "{{ ec2_region }}"
    #     state: absent
    #     instance_ids: "{{ untagged_instances }}"
    #   when: untagged_instances | length  > 0
