---
- hosts: localhost
  connection: local
  vars:
    date_later: 2020-01-05 08:30:00
    date_earlier: 2020-01-05 06:50:00
    aws_time: "2020-10-27T16:50:18+00:00"
    local_time: "{{ ansible_date_time.iso8601[:19] | to_datetime('%Y-%m-%dT%H:%M:%S') }}"
  tasks:
    - name: subtraction test
      debug:
        msg: "{{ ( (date_later - date_earlier).total_seconds() / 3600 ) }}"

    - name: local time print
      debug:
        msg: "{{ local_time }}"

    - name: aws time
      debug:
        msg: "{{ aws_time[:19] }}"

    - name: math task
      debug:
        msg: "{{ (ansible_date_time.iso8601[:19] | to_datetime('%Y-%m-%dT%H:%M:%S') - aws_time[:19] | to_datetime('%Y-%m-%dT%H:%M:%S')).total_seconds() / 3600 }}"

    #    (ansible_date_time.iso8601 - ec2_launch_time[:19] | to_datetime('%Y-%m-%dT%H:%M:%S')).total_seconds() / 3600
