---
- name: this Ansible Playbook will stop ec2 instances over killtime
  hosts: localhost
  gather_facts: false
  vars:
    ec2_region: "{{ your_region | default('us-east-1') }}"
    kill_time: "{{ your_kill_time | default('121') }}"
  tasks:
    # retrieve instances for VPC 1
    - name: grab info
      community.aws.ec2_instance_info:
        region: "{{ ec2_region }}"
        uptime: "{{ kill_time }}"
        filters:
          instance-state-name: [ "running" ]
          "tag:ansible-workshops": true
      register: ec2_node_info

    - name: diplay AWS uptime results
      debug:
        msg: "{{ lookup('template', 'templates/display.j2') }}"

    - name: stop every running running more than killtime
      ec2:
        region: "{{ ec2_region }}"
        state: stopped
        instance_ids: "{{ ec2_node_info.instances | map(attribute='instance_id') | list }}"
      when: ec2_node_info.instances | length  > 0
